=== DinizOliveira/Exercicios_XML/Exercicio 2/receita.xsd
<?xml version="1.0"?>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xs:element name="receita">
            <xs:element name="paciente">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="clinica" type="xs:string"/>
                        <xs:element name="paciente" type="xs:string"/>
                        <xs:element name="nome" type="xs:string"/>
                        <xs:element name="idade" type="xs:integer"/>
                        <xs:element name="medicamento" type="xs:string"/>
                        <xs:element name="descrição" type="xs:string"/>
                        <xs:element name="tipouso" type="xs:string"/>
                        <xs:element name="possologia" type="xs:string"/>
                        <xs:element name="data" type="xs:date"/>
                        <xs:element name="responsavel" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:element>
    </xsd:schema>
</xml>

=== DinizOliveira/Exercicios_XML/Exercicio 2/receita.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Exemplo de Comentário em XML -->
<receita xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="receita.xsd">
    <paciente>
        <clinica> Clinica Vitae </clinica>
        <nome> Natalia </nome>
        <idade> 19 </idade>
        <medicamento> Neosaldina e Dorflex </medicamento>
        <descrição> medicamentos com atividade analgésica </descrição>
        <tipouso> oral </tipouso>
        <possologia> Um comprimido a cada 8 horas </possologia>
        <data>12/06/2021</data>
        <responsavel> Dr. Fernando </responsavel>
    </paciente>
</receita>
